<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Override copy behaviour for Local.json (SDK already includes it, just update the metadata) -->
    <Content Update="appsettings.Local.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"                    Version="10.*" />
    <PackageReference Include="Scalar.AspNetCore"                               Version="2.*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"  Version="11.*" />
    <PackageReference Include="MediatR"                                         Version="12.*" />
    <PackageReference Include="Serilog.AspNetCore"                              Version="9.*" />
    <PackageReference Include="Serilog.Sinks.Console"                           Version="6.*" />
    <PackageReference Include="Serilog.Sinks.Seq"                               Version="8.*" />
    <PackageReference Include="Serilog.Enrichers.Environment"                   Version="3.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"             Version="9.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Softaxis.Identity.Application\Softaxis.Identity.Application.csproj" />
    <ProjectReference Include="..\Softaxis.Identity.Infrastructure\Softaxis.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Softaxis.BuildingBlocks.Infrastructure\Softaxis.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
