// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Softaxis.Inventory.Infrastructure.Persistence;

#nullable disable

namespace Softaxis.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260526000004_AddStockTransfers")]
    partial class AddStockTransfers { }
}
