import type { NavGroup } from "@/types";

export const navigationConfig: NavGroup[] = [
  {
    id: "core",
    label: "Core",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        labelAr: "لوحة التحكم",
        href: "/dashboard",
        icon: "LayoutDashboard",
        module: "dashboard",
      },
      {
        id: "ai-assistant",
        label: "AI Assistant",
        labelAr: "المساعد الذكي",
        href: "/ai-assistant",
        icon: "Sparkles",
        module: "ai-assistant",
        isNew: true,
        badge: "AI",
        badgeVariant: "default",
      },
      {
        id: "reports",
        label: "Reports",
        labelAr: "التقارير",
        href: "/reports",
        icon: "BarChart3",
        module: "reports",
      },
      {
        id: "file-manager",
        label: "File Manager",
        labelAr: "مدير الملفات",
        href: "/file-manager",
        icon: "FolderOpen",
        module: "file-manager",
      },
    ],
  },
  {
    id: "project-management-group",
    label: "Projects",
    items: [
      {
        id: "project-management",
        label: "Project Management",
        labelAr: "إدارة المشاريع",
        href: "/project-management",
        icon: "FolderKanban",
        module: "project-management",
      },
    ],
  },
  {
    id: "visa-group",
    label: "Visa Services",
    items: [
      {
        id: "visa",
        label: "Visa Services",
        labelAr: "خدمات التأشيرات",
        icon: "Stamp",
        module: "visa",
        children: [
          { id: "visa-dashboard", label: "Dashboard", labelAr: "لوحة التحكم", href: "/visa/dashboard", icon: "BarChart3" },
          { id: "visa-cases",     label: "Cases",      labelAr: "المعاملات",   href: "/visa/cases",     icon: "Stamp" },
          { id: "visa-renewals",  label: "Renewals",   labelAr: "التجديدات",   href: "/visa/renewals",  icon: "CalendarClock" },
          { id: "visa-types",     label: "Visa Types", labelAr: "أنواع التأشيرات", href: "/visa/types", icon: "ListChecks" },
          { id: "visa-channels",  label: "Channels",   labelAr: "قنوات الحكومة", href: "/visa/channels", icon: "Plug" },
        ],
      },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    items: [
      {
        id: "finance",
        label: "Finance",
        labelAr: "المالية",
        icon: "DollarSign",
        module: "finance",
        children: [
          {
            id: "accounting",
            label: "Accounting",
            labelAr: "المحاسبة",
            href: "/finance/accounting",
            icon: "BookOpen",
          },
          {
            id: "general-ledger",
            label: "General Ledger",
            labelAr: "دفتر الأستاذ",
            href: "/finance/general-ledger",
            icon: "Layers",
          },
          {
            id: "journals",
            label: "Journal Entries",
            labelAr: "القيود اليومية",
            href: "/finance/journals",
            icon: "FileText",
          },
          {
            id: "financial-statements",
            label: "Financial Statements",
            labelAr: "القوائم المالية",
            href: "/finance/statements",
            icon: "BarChart3",
          },
          {
            id: "invoicing",
            label: "Invoicing",
            labelAr: "الفواتير",
            href: "/finance/invoicing",
            icon: "Receipt",
            badge: 12,
            badgeVariant: "warning",
          },
          {
            id: "recurring-invoices",
            label: "Recurring Invoices",
            labelAr: "الفواتير المتكررة",
            href: "/finance/recurring",
            icon: "Repeat",
          },
          {
            id: "expenses",
            label: "Expenses",
            labelAr: "المصروفات",
            href: "/finance/expenses",
            icon: "CreditCard",
          },
          {
            id: "budgeting",
            label: "Budgeting",
            labelAr: "الميزانية",
            href: "/finance/budgeting",
            icon: "PieChart",
          },
          {
            id: "tax-vat",
            label: "Tax & VAT",
            labelAr: "الضرائب وضريبة القيمة المضافة",
            href: "/finance/tax",
            icon: "Percent",
          },
          {
            id: "bank-accounts",
            label: "Bank & Cash",
            labelAr: "البنك والنقد",
            href: "/finance/banking",
            icon: "Landmark",
          },
        ],
      },
    ],
  },
  {
    id: "people",
    label: "People",
    items: [
      {
        id: "hr",
        label: "HR & Payroll",
        labelAr: "الموارد البشرية والرواتب",
        icon: "Users",
        module: "hr",
        children: [
          {
            id: "employees",
            label: "Employees",
            labelAr: "الموظفون",
            href: "/hr/employees",
            icon: "UserCheck",
          },
          {
            id: "attendance",
            label: "Attendance",
            labelAr: "الحضور والغياب",
            href: "/hr/attendance",
            icon: "Clock",
          },
          {
            id: "payroll",
            label: "Payroll",
            labelAr: "الرواتب",
            href: "/hr/payroll",
            icon: "Banknote",
            badge: "Due",
            badgeVariant: "warning",
          },
          {
            id: "leaves",
            label: "Leave Management",
            labelAr: "إدارة الإجازات",
            href: "/hr/leaves",
            icon: "CalendarOff",
          },
          {
            id: "recruitment",
            label: "Recruitment",
            labelAr: "التوظيف",
            href: "/hr/recruitment",
            icon: "UserPlus",
          },
          {
            id: "performance",
            label: "Performance",
            labelAr: "الأداء",
            href: "/hr/performance",
            icon: "TrendingUp",
            isBeta: true,
          },
        ],
      },
      {
        id: "crm",
        label: "CRM",
        labelAr: "إدارة علاقات العملاء",
        icon: "Handshake",
        module: "crm",
        children: [
          {
            id: "crm-dashboard",
            label: "Dashboard",
            labelAr: "لوحة التحكم",
            href: "/crm/dashboard",
            icon: "BarChart3",
          },
          {
            id: "leads",
            label: "Leads",
            labelAr: "العملاء المحتملون",
            href: "/crm/leads",
            icon: "UserSearch",
          },
          {
            id: "pipeline",
            label: "Pipeline",
            labelAr: "خط الأنابيب",
            href: "/crm/pipeline",
            icon: "Workflow",
          },
          {
            id: "customers",
            label: "Customers",
            labelAr: "العملاء",
            href: "/crm/customers",
            icon: "Building2",
          },
          {
            id: "crm-activities",
            label: "Activities",
            labelAr: "الأنشطة",
            href: "/crm/activities",
            icon: "ListChecks",
          },
          {
            id: "crm-documents",
            label: "Documents",
            labelAr: "المستندات",
            href: "/crm/documents",
            icon: "FolderOpen",
          },
        ],
      },
    ],
  },
  {
    id: "operations",
    label: "Operations",
    items: [
      {
        id: "sales",
        label: "Sales",
        labelAr: "المبيعات",
        icon: "ShoppingBag",
        module: "sales",
        children: [
          {
            id: "quotations",
            label: "Quotations",
            labelAr: "عروض الأسعار",
            href: "/sales/quotations",
            icon: "FileSearch",
          },
          {
            id: "sales-orders",
            label: "Sales Orders",
            labelAr: "أوامر البيع",
            href: "/sales/orders",
            icon: "ClipboardList",
          },
          {
            id: "delivery-challans",
            label: "Delivery Challans",
            labelAr: "إشعارات التسليم",
            href: "/sales/delivery-challans",
            icon: "Truck",
          },
          {
            id: "returns",
            label: "Returns",
            labelAr: "المرتجعات",
            href: "/sales/returns",
            icon: "RotateCcw",
          },
        ],
      },
      {
        id: "purchase",
        label: "Purchase",
        labelAr: "المشتريات",
        icon: "ShoppingCart",
        module: "purchase",
        children: [
          {
            id: "vendors",
            label: "Vendors",
            labelAr: "الموردون",
            href: "/purchase/vendors",
            icon: "Truck",
          },
          {
            id: "purchase-orders",
            label: "Purchase Orders",
            labelAr: "أوامر الشراء",
            href: "/purchase/orders",
            icon: "ClipboardCheck",
            badge: 5,
            badgeVariant: "default",
          },
          {
            id: "grn",
            label: "Goods Receipt Notes",
            labelAr: "إشعارات استلام البضائع",
            href: "/purchase/grn",
            icon: "PackageCheck",
          },
          {
            id: "purchase-returns",
            label: "Purchase Returns",
            labelAr: "مرتجعات المشتريات",
            href: "/purchase/returns",
            icon: "RotateCcw",
          },
          {
            id: "purchase-bills",
            label: "Purchase Invoices",
            labelAr: "فواتير المشتريات",
            href: "/purchase/bills",
            icon: "Receipt",
          },
          {
            id: "approvals",
            label: "Approvals",
            labelAr: "الموافقات",
            href: "/purchase/approvals",
            icon: "CheckCircle2",
          },
        ],
      },
      {
        id: "inventory",
        label: "Inventory",
        labelAr: "المخزون",
        icon: "Package",
        module: "inventory",
        children: [
          {
            id: "warehouses",
            label: "Warehouses",
            labelAr: "المستودعات",
            href: "/inventory/warehouses",
            icon: "Warehouse",
          },
          {
            id: "stock",
            label: "Stock Items",
            labelAr: "المخزون",
            href: "/inventory/stock",
            icon: "Boxes",
          },
          {
            id: "movements",
            label: "Movements",
            labelAr: "حركات المخزون",
            href: "/inventory/movements",
            icon: "TrendingUp",
          },
          {
            id: "transfers",
            label: "Transfers",
            labelAr: "التحويلات",
            href: "/inventory/transfers",
            icon: "ArrowLeftRight",
          },
          {
            id: "inv-categories",
            label: "Categories",
            labelAr: "الفئات",
            href: "/inventory/master/categories",
            icon: "FolderTree",
          },
          {
            id: "inv-brands",
            label: "Brands",
            labelAr: "العلامات التجارية",
            href: "/inventory/master/brands",
            icon: "Tag",
          },
          {
            id: "inv-uom",
            label: "Units of Measure",
            labelAr: "وحدات القياس",
            href: "/inventory/master/uom",
            icon: "Ruler",
          },
        ],
      },
    ],
  },
  {
    id: "industry",
    label: "Industry Modules",
    items: [
      {
        id: "real-estate",
        label: "Real Estate",
        labelAr: "العقارات",
        icon: "Building",
        module: "real-estate",
        children: [
          { id: "re-sales", label: "Sales Pipeline", href: "/real-estate/sales", icon: "Handshake" },
          { id: "properties", label: "Properties", href: "/real-estate/properties", icon: "Home" },
          { id: "units", label: "Units", href: "/real-estate/units", icon: "DoorOpen" },
          { id: "tenants", label: "Tenants", href: "/real-estate/tenants", icon: "Users" },
          { id: "contracts", label: "Contracts", href: "/real-estate/contracts", icon: "FileSignature" },
          { id: "brokers", label: "Brokers", href: "/real-estate/brokers", icon: "Handshake" },
        ],
      },
      {
        id: "construction",
        label: "Construction",
        labelAr: "البناء والمقاولات",
        icon: "HardHat",
        module: "construction",
        children: [
          { id: "con-bidding", label: "Bidding & Contracts", href: "/construction/bidding", icon: "FileSignature" },
          { id: "projects", label: "Projects", href: "/construction/projects", icon: "FolderKanban" },
          { id: "boq", label: "BOQ", href: "/construction/boq", icon: "ListChecks" },
          { id: "contractors", label: "Contractors", href: "/construction/contractors", icon: "Hammer" },
          { id: "site-management", label: "Site Management", href: "/construction/sites", icon: "MapPin" },
        ],
      },
      {
        id: "healthcare",
        label: "Healthcare",
        labelAr: "الرعاية الصحية",
        icon: "Activity",
        module: "healthcare",
        children: [
          { id: "hc-patients", label: "Patients & Care", href: "/healthcare", icon: "Activity" },
        ],
      },
      {
        id: "education",
        label: "Education",
        labelAr: "التعليم",
        icon: "BookOpen",
        module: "education",
        children: [
          { id: "edu-main", label: "Admissions & Students", href: "/education", icon: "BookOpen" },
        ],
      },
      {
        id: "insurance",
        label: "Insurance",
        labelAr: "التأمين",
        icon: "ShieldCheck",
        module: "insurance",
        children: [
          { id: "ins-main", label: "Policies & Claims", href: "/insurance", icon: "ShieldCheck" },
        ],
      },
      {
        id: "b2b",
        label: "B2B Services",
        labelAr: "خدمات B2B",
        icon: "Briefcase",
        module: "b2b",
        children: [
          { id: "b2b-main", label: "Proposals & Contracts", href: "/b2b", icon: "Briefcase" },
        ],
      },
      {
        id: "hospitality",
        label: "Hospitality",
        labelAr: "الضيافة",
        icon: "Hotel",
        module: "hospitality",
        isBeta: true,
        children: [
          { id: "bookings", label: "Bookings", href: "/hospitality/bookings", icon: "CalendarCheck" },
          { id: "rooms", label: "Rooms", href: "/hospitality/rooms", icon: "BedDouble" },
          { id: "housekeeping", label: "Housekeeping", href: "/hospitality/housekeeping", icon: "SprayCan" },
        ],
      },
      {
        id: "pos",
        label: "Point of Sale",
        labelAr: "نقطة البيع",
        icon: "Monitor",
        module: "pos",
        children: [
          // module: "pos" → visible to all with POS access (cashier, supervisor, manager)
          { id: "retail-pos",      label: "Retail POS",      href: "/pos/retail",      icon: "ShoppingBag",     module: "pos" },
          { id: "pos-customers",   label: "Customers",       href: "/pos/customers",   icon: "Users",           module: "pos" },
          // module: "restaurant" → only visible to users with restaurant module access
          { id: "restaurant-pos",  label: "Restaurant POS",  href: "/pos/restaurant",  icon: "UtensilsCrossed", module: "restaurant" },
          { id: "kitchen-display", label: "Kitchen Display",  href: "/pos/kitchen",     icon: "ChefHat",         module: "restaurant" },
          { id: "floor-designer",  label: "Floor & Tables",  href: "/pos/floor-designer", icon: "LayoutGrid",   module: "restaurant" },
          { id: "waitlist",        label: "Waitlist",        href: "/pos/waitlist",    icon: "Clock",           module: "restaurant" },
          { id: "reservations",    label: "Reservations",    href: "/pos/reservations", icon: "CalendarClock",  module: "restaurant" },
          { id: "menu-management", label: "Menu Management", href: "/pos/menu-management", icon: "BookOpen",    module: "restaurant" },
          { id: "kitchen-config",  label: "Kitchen Config",  href: "/pos/kitchen-config", icon: "Printer",      module: "restaurant" },
          { id: "delivery",        label: "Delivery",        href: "/pos/delivery",     icon: "Truck",          module: "restaurant" },
          { id: "restaurant-reports",    label: "Reports",    href: "/pos/reports",      icon: "BarChart3",      module: "restaurant" },
          { id: "restaurant-dashboards", label: "Dashboards", href: "/pos/dashboards",   icon: "LayoutDashboard",module: "restaurant" },
          { id: "restaurant-branch-access", label: "Branch Access", href: "/pos/branch-access", icon: "Building2", module: "restaurant" },
        ],
      },
      {
        id: "recipe",
        label: "Recipe",
        labelAr: "الوصفات",
        icon: "ChefHat",
        module: "recipe",
        children: [
          { id: "recipes",     label: "Recipes",     href: "/recipe/recipes",     icon: "BookOpen" },
          { id: "ingredients", label: "Ingredients", href: "/recipe/ingredients", icon: "Package"  },
          { id: "food-cost",   label: "Food Cost",   href: "/recipe/food-cost",  icon: "Receipt" },
        ],
      },
    ],
  },
  {
    id: "master-data-group",
    label: "Data",
    items: [
      {
        id: "master-data",
        label: "Master Data",
        labelAr: "البيانات الأساسية",
        href: "/master-data",
        icon: "Database",
        module: "settings",
        badge: "New",
        badgeVariant: "default",
      },
    ],
  },
  {
    id: "system",
    label: "System",
    items: [
      {
        id: "super-admin",
        label: "Super Admin",
        labelAr: "المسؤول الرئيسي",
        href: "/super-admin",
        icon: "Building2",
        module: "super-admin",
        badge: "SA",
        badgeVariant: "default" as const,
      },
      {
        id: "settings",
        label: "Settings",
        labelAr: "الإعدادات",
        href: "/settings",
        icon: "Settings2",
        module: "settings",
        children: [
          { id: "general", label: "General", href: "/settings/general", icon: "SlidersHorizontal" },
          { id: "currency", label: "Currency & Rates", href: "/settings/currency", icon: "Coins" },
          { id: "billing", label: "Billing & Plan", href: "/settings/billing", icon: "CreditCard" },
          { id: "pos-payment-methods", label: "POS Payments", href: "/settings/pos-payment-methods", icon: "CreditCard", module: "pos" },
          { id: "payment-gateway", label: "Payment Gateway", href: "/settings/payment-gateway", icon: "Landmark", module: "pos" },
          { id: "notifications", label: "SMS & WhatsApp", href: "/settings/notifications", icon: "Bell", module: "restaurant" },
          { id: "devices", label: "Registered Devices", href: "/settings/devices", icon: "Monitor", module: "restaurant" },
          { id: "vouchers", label: "Vouchers & Coupons", href: "/settings/vouchers", icon: "Ticket", module: "pos" },
          { id: "users", label: "Users", href: "/settings/users", icon: "Users" },
          { id: "roles", label: "Roles & Permissions", href: "/settings/roles", icon: "ShieldCheck" },
          { id: "security", label: "Security (2FA)", href: "/settings/security", icon: "ShieldCheck" },
          { id: "branches", label: "Branches", href: "/settings/branches", icon: "GitBranch" },
          { id: "integrations", label: "Integrations", href: "/settings/integrations", icon: "Plug" },
          { id: "audit-logs", label: "Audit Logs", href: "/settings/audit", icon: "ScrollText" },
        ],
      },
    ],
  },
];
