// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Softaxis.Finance.Infrastructure.Persistence;

#nullable disable

namespace Softaxis.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260526000001_AddBankingAndTax")]
    partial class AddBankingAndTax
    {
    }
}
