// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Softaxis.CRM.Infrastructure.Persistence;

#nullable disable

namespace Softaxis.CRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260526000005_InitialCreate")]
    partial class InitialCreate { }
}
