// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Softaxis.RealEstate.Infrastructure.Persistence;

#nullable disable

namespace Softaxis.RealEstate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20260526000007_InitialCreate")]
    partial class InitialCreate { }
}
