import type { NavGroup } from "@/types";

export const navigationConfig: NavGroup[] = [
  {
    id: "core",
    label: "Core",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        labelAr: "لوحة التحكم",
        href: "/dashboard",
        icon: "LayoutDashboard",
        module: "dashboard",
      },
      {
        id: "ai-assistant",
        label: "AI Assistant",
        labelAr: "المساعد الذكي",
        href: "/ai-assistant",
        icon: "Sparkles",
        module: "ai-assistant",
        isNew: true,
        badge: "AI",
        badgeVariant: "default",
      },
      {
        id: "reports",
        label: "Reports",
        labelAr: "التقارير",
        href: "/reports",
        icon: "BarChart3",
        module: "reports",
      },
      {
        id: "file-manager",
        label: "File Manager",
        labelAr: "مدير الملفات",
        href: "/file-manager",
        icon: "FolderOpen",
        module: "file-manager",
      },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    items: [
      {
        id: "finance",
        label: "Finance",
        labelAr: "المالية",
        icon: "DollarSign",
        module: "finance",
        children: [
          {
            id: "accounting",
            label: "Accounting",
            labelAr: "المحاسبة",
            href: "/finance/accounting",
            icon: "BookOpen",
          },
          {
            id: "general-ledger",
            label: "General Ledger",
            labelAr: "دفتر الأستاذ",
            href: "/finance/general-ledger",
            icon: "Layers",
          },
          {
            id: "journals",
            label: "Journal Entries",
            labelAr: "القيود اليومية",
            href: "/finance/journals",
            icon: "FileText",
          },
          {
            id: "invoicing",
            label: "Invoicing",
            labelAr: "الفواتير",
            href: "/finance/invoicing",
            icon: "Receipt",
            badge: 12,
            badgeVariant: "warning",
          },
          {
            id: "expenses",
            label: "Expenses",
            labelAr: "المصروفات",
            href: "/finance/expenses",
            icon: "CreditCard",
          },
          {
            id: "budgeting",
            label: "Budgeting",
            labelAr: "الميزانية",
            href: "/finance/budgeting",
            icon: "PieChart",
          },
          {
            id: "tax-vat",
            label: "Tax & VAT",
            labelAr: "الضرائب وضريبة القيمة المضافة",
            href: "/finance/tax",
            icon: "Percent",
          },
          {
            id: "bank-accounts",
            label: "Bank & Cash",
            labelAr: "البنك والنقد",
            href: "/finance/banking",
            icon: "Landmark",
          },
        ],
      },
    ],
  },
  {
    id: "people",
    label: "People",
    items: [
      {
        id: "hr",
        label: "HR & Payroll",
        labelAr: "الموارد البشرية والرواتب",
        icon: "Users",
        module: "hr",
        children: [
          {
            id: "employees",
            label: "Employees",
            labelAr: "الموظفون",
            href: "/hr/employees",
            icon: "UserCheck",
          },
          {
            id: "attendance",
            label: "Attendance",
            labelAr: "الحضور والغياب",
            href: "/hr/attendance",
            icon: "Clock",
          },
          {
            id: "payroll",
            label: "Payroll",
            labelAr: "الرواتب",
            href: "/hr/payroll",
            icon: "Banknote",
            badge: "Due",
            badgeVariant: "warning",
          },
          {
            id: "leaves",
            label: "Leave Management",
            labelAr: "إدارة الإجازات",
            href: "/hr/leaves",
            icon: "CalendarOff",
          },
          {
            id: "recruitment",
            label: "Recruitment",
            labelAr: "التوظيف",
            href: "/hr/recruitment",
            icon: "UserPlus",
          },
          {
            id: "performance",
            label: "Performance",
            labelAr: "الأداء",
            href: "/hr/performance",
            icon: "TrendingUp",
            isBeta: true,
          },
        ],
      },
      {
        id: "crm",
        label: "CRM",
        labelAr: "إدارة علاقات العملاء",
        icon: "Handshake",
        module: "crm",
        children: [
          {
            id: "leads",
            label: "Leads",
            labelAr: "العملاء المحتملون",
            href: "/crm/leads",
            icon: "UserSearch",
          },
          {
            id: "pipeline",
            label: "Pipeline",
            labelAr: "خط الأنابيب",
            href: "/crm/pipeline",
            icon: "Workflow",
          },
          {
            id: "customers",
            label: "Customers",
            labelAr: "العملاء",
            href: "/crm/customers",
            icon: "Building2",
          },
        ],
      },
    ],
  },
  {
    id: "operations",
    label: "Operations",
    items: [
      {
        id: "sales",
        label: "Sales",
        labelAr: "المبيعات",
        icon: "ShoppingBag",
        module: "sales",
        children: [
          {
            id: "quotations",
            label: "Quotations",
            labelAr: "عروض الأسعار",
            href: "/sales/quotations",
            icon: "FileSearch",
          },
          {
            id: "sales-orders",
            label: "Sales Orders",
            labelAr: "أوامر البيع",
            href: "/sales/orders",
            icon: "ClipboardList",
          },
          {
            id: "returns",
            label: "Returns",
            labelAr: "المرتجعات",
            href: "/sales/returns",
            icon: "RotateCcw",
          },
        ],
      },
      {
        id: "purchase",
        label: "Purchase",
        labelAr: "المشتريات",
        icon: "ShoppingCart",
        module: "purchase",
        children: [
          {
            id: "vendors",
            label: "Vendors",
            labelAr: "الموردون",
            href: "/purchase/vendors",
            icon: "Truck",
          },
          {
            id: "purchase-orders",
            label: "Purchase Orders",
            labelAr: "أوامر الشراء",
            href: "/purchase/orders",
            icon: "ClipboardCheck",
            badge: 5,
            badgeVariant: "default",
          },
          {
            id: "approvals",
            label: "Approvals",
            labelAr: "الموافقات",
            href: "/purchase/approvals",
            icon: "CheckCircle2",
          },
        ],
      },
      {
        id: "inventory",
        label: "Inventory",
        labelAr: "المخزون",
        icon: "Package",
        module: "inventory",
        children: [
          {
            id: "warehouses",
            label: "Warehouses",
            labelAr: "المستودعات",
            href: "/inventory/warehouses",
            icon: "Warehouse",
          },
          {
            id: "stock",
            label: "Stock Items",
            labelAr: "المخزون",
            href: "/inventory/stock",
            icon: "Boxes",
          },
          {
            id: "movements",
            label: "Movements",
            labelAr: "حركات المخزون",
            href: "/inventory/movements",
            icon: "TrendingUp",
          },
          {
            id: "transfers",
            label: "Transfers",
            labelAr: "التحويلات",
            href: "/inventory/transfers",
            icon: "ArrowLeftRight",
          },
          {
            id: "inv-categories",
            label: "Categories",
            labelAr: "الفئات",
            href: "/inventory/master/categories",
            icon: "FolderTree",
          },
          {
            id: "inv-brands",
            label: "Brands",
            labelAr: "العلامات التجارية",
            href: "/inventory/master/brands",
            icon: "Tag",
          },
          {
            id: "inv-uom",
            label: "Units of Measure",
            labelAr: "وحدات القياس",
            href: "/inventory/master/uom",
            icon: "Ruler",
          },
        ],
      },
    ],
  },
  {
    id: "industry",
    label: "Industry Modules",
    items: [
      {
        id: "real-estate",
        label: "Real Estate",
        labelAr: "العقارات",
        icon: "Building",
        module: "real-estate",
        children: [
          { id: "properties", label: "Properties", href: "/real-estate/properties", icon: "Home" },
          { id: "units", label: "Units", href: "/real-estate/units", icon: "DoorOpen" },
          { id: "tenants", label: "Tenants", href: "/real-estate/tenants", icon: "Users" },
          { id: "contracts", label: "Contracts", href: "/real-estate/contracts", icon: "FileSignature" },
          { id: "brokers", label: "Brokers", href: "/real-estate/brokers", icon: "Handshake" },
        ],
      },
      {
        id: "construction",
        label: "Construction",
        labelAr: "البناء والمقاولات",
        icon: "HardHat",
        module: "construction",
        children: [
          { id: "projects", label: "Projects", href: "/construction/projects", icon: "FolderKanban" },
          { id: "boq", label: "BOQ", href: "/construction/boq", icon: "ListChecks" },
          { id: "contractors", label: "Contractors", href: "/construction/contractors", icon: "Hammer" },
          { id: "site-management", label: "Site Management", href: "/construction/sites", icon: "MapPin" },
        ],
      },
      {
        id: "hospitality",
        label: "Hospitality",
        labelAr: "الضيافة",
        icon: "Hotel",
        module: "hospitality",
        isBeta: true,
        children: [
          { id: "bookings", label: "Bookings", href: "/hospitality/bookings", icon: "CalendarCheck" },
          { id: "rooms", label: "Rooms", href: "/hospitality/rooms", icon: "BedDouble" },
          { id: "housekeeping", label: "Housekeeping", href: "/hospitality/housekeeping", icon: "SprayCan" },
        ],
      },
      {
        id: "pos",
        label: "Point of Sale",
        labelAr: "نقطة البيع",
        icon: "Monitor",
        module: "pos",
        children: [
          { id: "retail-pos", label: "Retail POS", href: "/pos/retail", icon: "ShoppingBag" },
          { id: "restaurant-pos", label: "Restaurant POS", href: "/pos/restaurant", icon: "UtensilsCrossed" },
          { id: "kitchen-display", label: "Kitchen Display", href: "/pos/kitchen", icon: "ChefHat" },
        ],
      },
      {
        id: "recipe",
        label: "Recipe",
        labelAr: "الوصفات",
        icon: "ChefHat",
        module: "recipe",
        children: [
          { id: "recipes", label: "Recipes", href: "/recipe/recipes", icon: "BookOpen" },
          { id: "ingredients", label: "Ingredients", href: "/recipe/ingredients", icon: "Package" },
        ],
      },
    ],
  },
  {
    id: "system",
    label: "System",
    items: [
      {
        id: "settings",
        label: "Settings",
        labelAr: "الإعدادات",
        href: "/settings",
        icon: "Settings2",
        module: "settings",
        children: [
          { id: "general", label: "General", href: "/settings/general", icon: "SlidersHorizontal" },
          { id: "users", label: "Users", href: "/settings/users", icon: "Users" },
          { id: "roles", label: "Roles & Permissions", href: "/settings/roles", icon: "ShieldCheck" },
          { id: "branches", label: "Branches", href: "/settings/branches", icon: "GitBranch" },
          { id: "integrations", label: "Integrations", href: "/settings/integrations", icon: "Plug" },
          { id: "audit-logs", label: "Audit Logs", href: "/settings/audit", icon: "ScrollText" },
        ],
      },
    ],
  },
];
