<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Softaxis.RealEstate.Infrastructure\Softaxis.RealEstate.Infrastructure.csproj" />
    <ProjectReference Include="..\Softaxis.RealEstate.Application\Softaxis.RealEstate.Application.csproj" />
  </ItemGroup>
</Project>
