<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Softaxis.Sales.Domain\Softaxis.Sales.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Softaxis.BuildingBlocks.Application\Softaxis.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
