// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Softaxis.POS.Infrastructure.Persistence;

#nullable disable

namespace Softaxis.POS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20260603000001_DropLineItemProductFk")]
    partial class DropLineItemProductFk
    {
    }
}
