// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softaxis.Identity.Infrastructure.Persistence;

#nullable disable

namespace Softaxis.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260609120621_AddAuditLogTenantId")]
    partial class AddAuditLogTenantId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Key")
                        .IsUnique()
                        .HasFilter("[UserId] IS NULL");

                    b.HasIndex("Category", "Key", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("app_settings", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_immutable", "1=1");
                        });
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Manager")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OpenedDate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Staff")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("branches", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Action")
                        .IsUnique();

                    b.ToTable("permissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12d040d1-56fa-8c03-95d7-983522eca589"),
                            Action = "view",
                            Description = "View inventory stock",
                            ModuleId = "inventory.stock"
                        },
                        new
                        {
                            Id = new Guid("979535a2-c577-72a3-0a02-1505c6137bfd"),
                            Action = "create",
                            Description = "Create inventory stock",
                            ModuleId = "inventory.stock"
                        },
                        new
                        {
                            Id = new Guid("0d7bb139-0a34-c185-a1ea-eb62bbb5112f"),
                            Action = "edit",
                            Description = "Edit inventory stock",
                            ModuleId = "inventory.stock"
                        },
                        new
                        {
                            Id = new Guid("78f1f772-a581-9a0e-c41c-f2bb642e92fe"),
                            Action = "delete",
                            Description = "Delete inventory stock",
                            ModuleId = "inventory.stock"
                        },
                        new
                        {
                            Id = new Guid("4a91c1df-6ed2-3068-1eb5-d0f906a8340d"),
                            Action = "export",
                            Description = "Export inventory stock",
                            ModuleId = "inventory.stock"
                        },
                        new
                        {
                            Id = new Guid("2aab70c9-fabd-b8b0-9ce3-39be45c66c58"),
                            Action = "adjust",
                            Description = "Adjust inventory stock",
                            ModuleId = "inventory.stock"
                        },
                        new
                        {
                            Id = new Guid("dcae8e99-aa29-d21f-c7cb-d6668641613e"),
                            Action = "view",
                            Description = "View inventory warehouses",
                            ModuleId = "inventory.warehouses"
                        },
                        new
                        {
                            Id = new Guid("d97815c8-92c0-794d-6358-4d08130b4566"),
                            Action = "create",
                            Description = "Create inventory warehouses",
                            ModuleId = "inventory.warehouses"
                        },
                        new
                        {
                            Id = new Guid("94b139af-76e9-256a-d059-d86f449b1306"),
                            Action = "edit",
                            Description = "Edit inventory warehouses",
                            ModuleId = "inventory.warehouses"
                        },
                        new
                        {
                            Id = new Guid("806ea39b-dba2-df21-334a-f4d99377da0b"),
                            Action = "delete",
                            Description = "Delete inventory warehouses",
                            ModuleId = "inventory.warehouses"
                        },
                        new
                        {
                            Id = new Guid("5c325fdc-fff2-02fc-e3e8-c99164bc6d36"),
                            Action = "view",
                            Description = "View inventory movements",
                            ModuleId = "inventory.movements"
                        },
                        new
                        {
                            Id = new Guid("999557ec-2542-c0c4-d4b1-50756133ae3a"),
                            Action = "create",
                            Description = "Create inventory movements",
                            ModuleId = "inventory.movements"
                        },
                        new
                        {
                            Id = new Guid("09380234-5b0d-e57c-2f3b-4731527db4c6"),
                            Action = "export",
                            Description = "Export inventory movements",
                            ModuleId = "inventory.movements"
                        },
                        new
                        {
                            Id = new Guid("f4953692-968a-5af8-43c7-5034bb034fc8"),
                            Action = "adjust",
                            Description = "Adjust inventory movements",
                            ModuleId = "inventory.movements"
                        },
                        new
                        {
                            Id = new Guid("2bc6429d-df19-9dd1-66f4-c980e29d888c"),
                            Action = "view",
                            Description = "View inventory transfers",
                            ModuleId = "inventory.transfers"
                        },
                        new
                        {
                            Id = new Guid("949f5297-cb11-55fe-0577-363d69638021"),
                            Action = "create",
                            Description = "Create inventory transfers",
                            ModuleId = "inventory.transfers"
                        },
                        new
                        {
                            Id = new Guid("142c5ebb-c03f-6a5e-e240-05300eccb6f6"),
                            Action = "approve",
                            Description = "Approve inventory transfers",
                            ModuleId = "inventory.transfers"
                        },
                        new
                        {
                            Id = new Guid("761dbde0-90bf-5fe1-3491-a40123848e8f"),
                            Action = "export",
                            Description = "Export inventory transfers",
                            ModuleId = "inventory.transfers"
                        },
                        new
                        {
                            Id = new Guid("8a968a19-e34e-c6f9-d3c6-6e1773219874"),
                            Action = "view",
                            Description = "View pos sessions",
                            ModuleId = "pos.sessions"
                        },
                        new
                        {
                            Id = new Guid("8573d9f5-cdf9-9327-602a-02984606d445"),
                            Action = "create",
                            Description = "Create pos sessions",
                            ModuleId = "pos.sessions"
                        },
                        new
                        {
                            Id = new Guid("bd8e8f62-3e0f-0881-c4e3-c97e66587e51"),
                            Action = "approve",
                            Description = "Approve pos sessions",
                            ModuleId = "pos.sessions"
                        },
                        new
                        {
                            Id = new Guid("ebf79e7d-7ecb-4263-39aa-34c04ecbd8b4"),
                            Action = "view",
                            Description = "View pos transactions",
                            ModuleId = "pos.transactions"
                        },
                        new
                        {
                            Id = new Guid("1d400ab9-b01d-c5e9-e815-320ec777ae61"),
                            Action = "create",
                            Description = "Create pos transactions",
                            ModuleId = "pos.transactions"
                        },
                        new
                        {
                            Id = new Guid("0d73186c-9868-2b7c-64db-79677c668f9b"),
                            Action = "print",
                            Description = "Print pos transactions",
                            ModuleId = "pos.transactions"
                        },
                        new
                        {
                            Id = new Guid("c96b5653-6cac-645a-90bc-efadadad0234"),
                            Action = "void",
                            Description = "Void pos transactions",
                            ModuleId = "pos.transactions"
                        },
                        new
                        {
                            Id = new Guid("dc3ec71d-f469-730e-391a-699c2b68f888"),
                            Action = "refund",
                            Description = "Refund pos transactions",
                            ModuleId = "pos.transactions"
                        },
                        new
                        {
                            Id = new Guid("1b4f2ce0-c5ed-be7d-726c-e2325e8a519d"),
                            Action = "discount",
                            Description = "Discount pos transactions",
                            ModuleId = "pos.transactions"
                        },
                        new
                        {
                            Id = new Guid("25d6ff61-0de7-f925-a25a-eef7feae833e"),
                            Action = "view",
                            Description = "View pos products",
                            ModuleId = "pos.products"
                        },
                        new
                        {
                            Id = new Guid("798d7327-cf70-de73-8c56-253dcea1289c"),
                            Action = "create",
                            Description = "Create pos products",
                            ModuleId = "pos.products"
                        },
                        new
                        {
                            Id = new Guid("4ef3b94d-c1b2-c694-060c-89dac598021a"),
                            Action = "edit",
                            Description = "Edit pos products",
                            ModuleId = "pos.products"
                        },
                        new
                        {
                            Id = new Guid("7f298efc-8130-666c-2a94-8ce31baa7384"),
                            Action = "delete",
                            Description = "Delete pos products",
                            ModuleId = "pos.products"
                        },
                        new
                        {
                            Id = new Guid("ac7952a0-cbdf-56c2-fdb5-bfade4312a0b"),
                            Action = "view",
                            Description = "View pos reports",
                            ModuleId = "pos.reports"
                        },
                        new
                        {
                            Id = new Guid("43f41588-55f8-3c94-47b5-077a2eb7f11d"),
                            Action = "export",
                            Description = "Export pos reports",
                            ModuleId = "pos.reports"
                        },
                        new
                        {
                            Id = new Guid("9dc5dbba-794a-6de8-14bb-b8abf5376350"),
                            Action = "print",
                            Description = "Print pos reports",
                            ModuleId = "pos.reports"
                        },
                        new
                        {
                            Id = new Guid("845123ad-5481-b26b-0118-0a1e957b8a03"),
                            Action = "view",
                            Description = "View finance accounting",
                            ModuleId = "finance.accounting"
                        },
                        new
                        {
                            Id = new Guid("6a04e48d-fa7f-8fe9-3e0e-74edbbbb86e1"),
                            Action = "create",
                            Description = "Create finance accounting",
                            ModuleId = "finance.accounting"
                        },
                        new
                        {
                            Id = new Guid("d5e71685-7f8a-6037-e3b4-a9362bef7294"),
                            Action = "edit",
                            Description = "Edit finance accounting",
                            ModuleId = "finance.accounting"
                        },
                        new
                        {
                            Id = new Guid("3c08a1af-731a-2597-38b7-9c685fd844f5"),
                            Action = "delete",
                            Description = "Delete finance accounting",
                            ModuleId = "finance.accounting"
                        },
                        new
                        {
                            Id = new Guid("fd79a9bd-68d4-0f0f-f322-6571b1011db3"),
                            Action = "approve",
                            Description = "Approve finance accounting",
                            ModuleId = "finance.accounting"
                        },
                        new
                        {
                            Id = new Guid("84728a1a-f18b-73f9-6946-ebeb256a3812"),
                            Action = "export",
                            Description = "Export finance accounting",
                            ModuleId = "finance.accounting"
                        },
                        new
                        {
                            Id = new Guid("8508c5fc-ddb5-0975-d6dc-8b4b20efca03"),
                            Action = "view",
                            Description = "View finance gl",
                            ModuleId = "finance.gl"
                        },
                        new
                        {
                            Id = new Guid("1163928c-8faf-d6d0-7ac9-c6a8eb16d375"),
                            Action = "create",
                            Description = "Create finance gl",
                            ModuleId = "finance.gl"
                        },
                        new
                        {
                            Id = new Guid("99ced367-20ed-f493-7962-879dd4e5c414"),
                            Action = "edit",
                            Description = "Edit finance gl",
                            ModuleId = "finance.gl"
                        },
                        new
                        {
                            Id = new Guid("8289e208-9cff-175e-92f7-e6d70907f387"),
                            Action = "approve",
                            Description = "Approve finance gl",
                            ModuleId = "finance.gl"
                        },
                        new
                        {
                            Id = new Guid("88aff01f-acc0-552d-cff9-ff4da867c157"),
                            Action = "export",
                            Description = "Export finance gl",
                            ModuleId = "finance.gl"
                        },
                        new
                        {
                            Id = new Guid("55755526-b800-551b-7992-b01c80f84d3f"),
                            Action = "view",
                            Description = "View finance journals",
                            ModuleId = "finance.journals"
                        },
                        new
                        {
                            Id = new Guid("c151bc21-e8b1-4bcf-049c-85f43d2a2054"),
                            Action = "create",
                            Description = "Create finance journals",
                            ModuleId = "finance.journals"
                        },
                        new
                        {
                            Id = new Guid("47de56d8-7111-61ce-c5cd-4be228cebfaf"),
                            Action = "edit",
                            Description = "Edit finance journals",
                            ModuleId = "finance.journals"
                        },
                        new
                        {
                            Id = new Guid("90583b87-eb65-747a-c43c-3fb59f02fbc3"),
                            Action = "approve",
                            Description = "Approve finance journals",
                            ModuleId = "finance.journals"
                        },
                        new
                        {
                            Id = new Guid("c32f81ee-cc6a-b1f5-fc15-a5a4f83178a7"),
                            Action = "export",
                            Description = "Export finance journals",
                            ModuleId = "finance.journals"
                        },
                        new
                        {
                            Id = new Guid("450a40f0-1f43-ac4b-8696-44e8f9946791"),
                            Action = "print",
                            Description = "Print finance journals",
                            ModuleId = "finance.journals"
                        },
                        new
                        {
                            Id = new Guid("0b8987cb-2358-8f8f-aded-d9913b52d449"),
                            Action = "view",
                            Description = "View finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("52c817c4-3c58-13ff-30cf-8cb3f4a7181a"),
                            Action = "create",
                            Description = "Create finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("52ddb860-3193-6c3a-0ded-79ff611a879c"),
                            Action = "edit",
                            Description = "Edit finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("65741ea7-01d8-f15c-f88a-2340b6a7b32c"),
                            Action = "delete",
                            Description = "Delete finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("a4fe4013-b96e-0bb9-0f9c-44bd79b95c02"),
                            Action = "approve",
                            Description = "Approve finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("36f7a0d8-bb6b-ec6e-df3f-17ab3642397f"),
                            Action = "export",
                            Description = "Export finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("a76c1be4-f17b-6e9d-2aff-07ae11771b4b"),
                            Action = "print",
                            Description = "Print finance invoicing",
                            ModuleId = "finance.invoicing"
                        },
                        new
                        {
                            Id = new Guid("da82bd85-8e4e-ef72-ba4b-5b0afc5b7e1b"),
                            Action = "view",
                            Description = "View finance expenses",
                            ModuleId = "finance.expenses"
                        },
                        new
                        {
                            Id = new Guid("40e55301-1c6f-23f9-20bd-3a6c4f64d2ed"),
                            Action = "create",
                            Description = "Create finance expenses",
                            ModuleId = "finance.expenses"
                        },
                        new
                        {
                            Id = new Guid("83ef5fb5-ffe6-3ba9-c67a-cd1a5f962135"),
                            Action = "edit",
                            Description = "Edit finance expenses",
                            ModuleId = "finance.expenses"
                        },
                        new
                        {
                            Id = new Guid("cca9f732-e3b7-dcef-a839-9fbe553f467b"),
                            Action = "delete",
                            Description = "Delete finance expenses",
                            ModuleId = "finance.expenses"
                        },
                        new
                        {
                            Id = new Guid("2db15f6d-1d40-1f1f-7481-cac26cbb7248"),
                            Action = "approve",
                            Description = "Approve finance expenses",
                            ModuleId = "finance.expenses"
                        },
                        new
                        {
                            Id = new Guid("2039deff-d48a-7de1-a04c-66455068430e"),
                            Action = "export",
                            Description = "Export finance expenses",
                            ModuleId = "finance.expenses"
                        },
                        new
                        {
                            Id = new Guid("749f2090-dfa2-4817-b2f4-65df02f416a5"),
                            Action = "view",
                            Description = "View finance budgeting",
                            ModuleId = "finance.budgeting"
                        },
                        new
                        {
                            Id = new Guid("b9da45f5-1e8a-4c58-9538-b5203879a508"),
                            Action = "create",
                            Description = "Create finance budgeting",
                            ModuleId = "finance.budgeting"
                        },
                        new
                        {
                            Id = new Guid("b938f392-b592-0b05-6ca1-36fcaf076970"),
                            Action = "edit",
                            Description = "Edit finance budgeting",
                            ModuleId = "finance.budgeting"
                        },
                        new
                        {
                            Id = new Guid("98a99a98-e46c-35ca-f9b0-d563081a66f0"),
                            Action = "approve",
                            Description = "Approve finance budgeting",
                            ModuleId = "finance.budgeting"
                        },
                        new
                        {
                            Id = new Guid("bc854ce2-13bd-2582-1b91-539b749f48e5"),
                            Action = "export",
                            Description = "Export finance budgeting",
                            ModuleId = "finance.budgeting"
                        },
                        new
                        {
                            Id = new Guid("b6f689c0-e154-5dcb-bd9c-52aecd48f003"),
                            Action = "view",
                            Description = "View finance tax",
                            ModuleId = "finance.tax"
                        },
                        new
                        {
                            Id = new Guid("edc0de3f-6682-4a50-fbe1-d52e417196b5"),
                            Action = "create",
                            Description = "Create finance tax",
                            ModuleId = "finance.tax"
                        },
                        new
                        {
                            Id = new Guid("6b611978-9231-03e0-2a8d-55a255a5f4bf"),
                            Action = "edit",
                            Description = "Edit finance tax",
                            ModuleId = "finance.tax"
                        },
                        new
                        {
                            Id = new Guid("b5310148-f1f1-c1d7-da15-c8b6db74732f"),
                            Action = "approve",
                            Description = "Approve finance tax",
                            ModuleId = "finance.tax"
                        },
                        new
                        {
                            Id = new Guid("4337fccc-5f50-ebf0-7262-60cfc23d384a"),
                            Action = "export",
                            Description = "Export finance tax",
                            ModuleId = "finance.tax"
                        },
                        new
                        {
                            Id = new Guid("8ec6842e-fac7-53cc-9371-21711bf96e57"),
                            Action = "view",
                            Description = "View finance banking",
                            ModuleId = "finance.banking"
                        },
                        new
                        {
                            Id = new Guid("25ec787a-af3b-0042-f7dd-c0edc02c46e7"),
                            Action = "create",
                            Description = "Create finance banking",
                            ModuleId = "finance.banking"
                        },
                        new
                        {
                            Id = new Guid("631f2514-5a9b-4727-bc82-8addcbf31aee"),
                            Action = "edit",
                            Description = "Edit finance banking",
                            ModuleId = "finance.banking"
                        },
                        new
                        {
                            Id = new Guid("f2a0fdf3-679b-210c-4cec-96d3dc9af698"),
                            Action = "approve",
                            Description = "Approve finance banking",
                            ModuleId = "finance.banking"
                        },
                        new
                        {
                            Id = new Guid("e4924a1b-db2f-b479-b05b-80c1765b5301"),
                            Action = "export",
                            Description = "Export finance banking",
                            ModuleId = "finance.banking"
                        },
                        new
                        {
                            Id = new Guid("68c2c635-8f5e-3308-657a-d48bbb0d0006"),
                            Action = "view",
                            Description = "View hr employees",
                            ModuleId = "hr.employees"
                        },
                        new
                        {
                            Id = new Guid("b1dd8c02-0230-2ada-1a1b-6043300b5cea"),
                            Action = "create",
                            Description = "Create hr employees",
                            ModuleId = "hr.employees"
                        },
                        new
                        {
                            Id = new Guid("42799ff4-cd81-eb9f-599d-773d8d0fcc82"),
                            Action = "edit",
                            Description = "Edit hr employees",
                            ModuleId = "hr.employees"
                        },
                        new
                        {
                            Id = new Guid("d1688e62-55aa-645c-1f43-95e20cbeeae5"),
                            Action = "delete",
                            Description = "Delete hr employees",
                            ModuleId = "hr.employees"
                        },
                        new
                        {
                            Id = new Guid("9a7bcd5f-7ca1-5ecc-8510-916170531b40"),
                            Action = "export",
                            Description = "Export hr employees",
                            ModuleId = "hr.employees"
                        },
                        new
                        {
                            Id = new Guid("57f8682a-d2e1-48cd-1661-b1451acfa308"),
                            Action = "view",
                            Description = "View hr attendance",
                            ModuleId = "hr.attendance"
                        },
                        new
                        {
                            Id = new Guid("bea957d2-6f47-8847-9eaf-8ce5dd47b3a4"),
                            Action = "create",
                            Description = "Create hr attendance",
                            ModuleId = "hr.attendance"
                        },
                        new
                        {
                            Id = new Guid("702538eb-9040-0ad3-a670-1cb2f1f50675"),
                            Action = "edit",
                            Description = "Edit hr attendance",
                            ModuleId = "hr.attendance"
                        },
                        new
                        {
                            Id = new Guid("86ab676b-ee77-479c-1624-7bb6938decb9"),
                            Action = "export",
                            Description = "Export hr attendance",
                            ModuleId = "hr.attendance"
                        },
                        new
                        {
                            Id = new Guid("ea978f1f-ce9d-28b0-ee21-ab27de3a2264"),
                            Action = "adjust",
                            Description = "Adjust hr attendance",
                            ModuleId = "hr.attendance"
                        },
                        new
                        {
                            Id = new Guid("cfb192eb-36ba-8e2c-6238-503306b7c22d"),
                            Action = "view",
                            Description = "View hr payroll",
                            ModuleId = "hr.payroll"
                        },
                        new
                        {
                            Id = new Guid("08d6801a-51a4-d8b4-538e-9d60ff6eaf33"),
                            Action = "create",
                            Description = "Create hr payroll",
                            ModuleId = "hr.payroll"
                        },
                        new
                        {
                            Id = new Guid("0ed0ed95-f4e2-5bf5-f8cb-bf139d2e6392"),
                            Action = "approve",
                            Description = "Approve hr payroll",
                            ModuleId = "hr.payroll"
                        },
                        new
                        {
                            Id = new Guid("bc1adb71-bfd0-a90c-4a90-487f6488474a"),
                            Action = "export",
                            Description = "Export hr payroll",
                            ModuleId = "hr.payroll"
                        },
                        new
                        {
                            Id = new Guid("a488dc7e-080c-a214-6a38-dd8955ef38f1"),
                            Action = "print",
                            Description = "Print hr payroll",
                            ModuleId = "hr.payroll"
                        },
                        new
                        {
                            Id = new Guid("f4c76f95-669c-ed81-b309-9922036d5c71"),
                            Action = "view",
                            Description = "View hr leaves",
                            ModuleId = "hr.leaves"
                        },
                        new
                        {
                            Id = new Guid("00851cd9-e968-dee3-b939-92f20f225761"),
                            Action = "create",
                            Description = "Create hr leaves",
                            ModuleId = "hr.leaves"
                        },
                        new
                        {
                            Id = new Guid("cc2a0879-75f7-4230-69ec-928afde57097"),
                            Action = "edit",
                            Description = "Edit hr leaves",
                            ModuleId = "hr.leaves"
                        },
                        new
                        {
                            Id = new Guid("6a38fad5-dab3-5912-d9b0-2f23d976a156"),
                            Action = "approve",
                            Description = "Approve hr leaves",
                            ModuleId = "hr.leaves"
                        },
                        new
                        {
                            Id = new Guid("10b9c004-bd5d-a6dc-a6a6-08dc6c0d22c3"),
                            Action = "view",
                            Description = "View hr recruitment",
                            ModuleId = "hr.recruitment"
                        },
                        new
                        {
                            Id = new Guid("47876f94-8ed6-4615-08aa-90cb3f0140c3"),
                            Action = "create",
                            Description = "Create hr recruitment",
                            ModuleId = "hr.recruitment"
                        },
                        new
                        {
                            Id = new Guid("ccc9a5e7-e602-c0fd-3a97-8d1bfce9b427"),
                            Action = "edit",
                            Description = "Edit hr recruitment",
                            ModuleId = "hr.recruitment"
                        },
                        new
                        {
                            Id = new Guid("0a730d1f-5612-8b91-654d-31ea891064f7"),
                            Action = "delete",
                            Description = "Delete hr recruitment",
                            ModuleId = "hr.recruitment"
                        },
                        new
                        {
                            Id = new Guid("78b08b61-dd2e-4683-e4de-4d078a38825c"),
                            Action = "view",
                            Description = "View hr performance",
                            ModuleId = "hr.performance"
                        },
                        new
                        {
                            Id = new Guid("b6ad8a35-b8fb-798c-b9a2-9f6fdc493807"),
                            Action = "create",
                            Description = "Create hr performance",
                            ModuleId = "hr.performance"
                        },
                        new
                        {
                            Id = new Guid("9b07f66d-daf9-0955-59be-305f376fdf56"),
                            Action = "edit",
                            Description = "Edit hr performance",
                            ModuleId = "hr.performance"
                        },
                        new
                        {
                            Id = new Guid("a9bff2ba-d2ff-a758-e995-5139b3f1e767"),
                            Action = "export",
                            Description = "Export hr performance",
                            ModuleId = "hr.performance"
                        },
                        new
                        {
                            Id = new Guid("79a62438-f821-8421-cf3c-d56904f14bd0"),
                            Action = "view",
                            Description = "View crm leads",
                            ModuleId = "crm.leads"
                        },
                        new
                        {
                            Id = new Guid("b50c76d2-bedc-181d-0c0c-d66c681d41c2"),
                            Action = "create",
                            Description = "Create crm leads",
                            ModuleId = "crm.leads"
                        },
                        new
                        {
                            Id = new Guid("735e60ce-17e4-dbfd-cde1-358016347b9b"),
                            Action = "edit",
                            Description = "Edit crm leads",
                            ModuleId = "crm.leads"
                        },
                        new
                        {
                            Id = new Guid("a0f4acd9-3121-db4b-c620-c7aa71d2eaf8"),
                            Action = "delete",
                            Description = "Delete crm leads",
                            ModuleId = "crm.leads"
                        },
                        new
                        {
                            Id = new Guid("56d5f2b5-1c28-3c4f-8480-e6f56f8dc48b"),
                            Action = "export",
                            Description = "Export crm leads",
                            ModuleId = "crm.leads"
                        },
                        new
                        {
                            Id = new Guid("d527ca7a-af89-5749-b303-a7cb3df3f425"),
                            Action = "view",
                            Description = "View crm pipeline",
                            ModuleId = "crm.pipeline"
                        },
                        new
                        {
                            Id = new Guid("e266623d-f395-40bb-d92b-8ae64b393594"),
                            Action = "create",
                            Description = "Create crm pipeline",
                            ModuleId = "crm.pipeline"
                        },
                        new
                        {
                            Id = new Guid("1cdb57c8-b2c5-050e-3b48-352ecbd3253c"),
                            Action = "edit",
                            Description = "Edit crm pipeline",
                            ModuleId = "crm.pipeline"
                        },
                        new
                        {
                            Id = new Guid("7cd97338-5243-a31b-b03f-8a05f89c8fc6"),
                            Action = "export",
                            Description = "Export crm pipeline",
                            ModuleId = "crm.pipeline"
                        },
                        new
                        {
                            Id = new Guid("e2e0eda3-5001-071e-c9e1-9c3fc9eb2b5f"),
                            Action = "view",
                            Description = "View crm customers",
                            ModuleId = "crm.customers"
                        },
                        new
                        {
                            Id = new Guid("dc73e6c4-4878-f781-3315-66e1cb059e85"),
                            Action = "create",
                            Description = "Create crm customers",
                            ModuleId = "crm.customers"
                        },
                        new
                        {
                            Id = new Guid("d8010522-2afb-a9db-cb7f-4dca22798ac0"),
                            Action = "edit",
                            Description = "Edit crm customers",
                            ModuleId = "crm.customers"
                        },
                        new
                        {
                            Id = new Guid("f0b98871-2695-51e7-1a0d-b22ec71126c9"),
                            Action = "delete",
                            Description = "Delete crm customers",
                            ModuleId = "crm.customers"
                        },
                        new
                        {
                            Id = new Guid("0f02656c-0cda-3b8d-1830-3bb2d4de379f"),
                            Action = "export",
                            Description = "Export crm customers",
                            ModuleId = "crm.customers"
                        },
                        new
                        {
                            Id = new Guid("09dc5980-a3bd-e464-035f-5f2905d0aa5f"),
                            Action = "view",
                            Description = "View sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("35867692-e25e-1c77-7a77-65ab50c06a0e"),
                            Action = "create",
                            Description = "Create sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("8bea5bd6-3281-badc-9d37-c48c5e68304c"),
                            Action = "edit",
                            Description = "Edit sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("4b2e8910-911f-f2d5-4a88-c019a51f64d9"),
                            Action = "delete",
                            Description = "Delete sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("5b084af3-7561-b8ad-1f7d-277c7f394ba8"),
                            Action = "approve",
                            Description = "Approve sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("3766ec26-fc01-82da-62c8-879218601587"),
                            Action = "export",
                            Description = "Export sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("6124136a-7756-b13b-8a19-7b1b64c9773a"),
                            Action = "print",
                            Description = "Print sales quotations",
                            ModuleId = "sales.quotations"
                        },
                        new
                        {
                            Id = new Guid("d9a2807f-166a-c688-a170-ff95f319d303"),
                            Action = "view",
                            Description = "View sales orders",
                            ModuleId = "sales.orders"
                        },
                        new
                        {
                            Id = new Guid("421678da-7746-7031-3b42-13ebb17d3200"),
                            Action = "create",
                            Description = "Create sales orders",
                            ModuleId = "sales.orders"
                        },
                        new
                        {
                            Id = new Guid("5357e13f-c491-ccea-2062-2c548c61ba6e"),
                            Action = "edit",
                            Description = "Edit sales orders",
                            ModuleId = "sales.orders"
                        },
                        new
                        {
                            Id = new Guid("9f0f26ea-ac1d-05ee-ae2f-bfdd55cecaa1"),
                            Action = "approve",
                            Description = "Approve sales orders",
                            ModuleId = "sales.orders"
                        },
                        new
                        {
                            Id = new Guid("22c78c57-ae77-544d-b429-604a25d1868c"),
                            Action = "export",
                            Description = "Export sales orders",
                            ModuleId = "sales.orders"
                        },
                        new
                        {
                            Id = new Guid("b6cc81a9-56bb-042c-37e3-129a6d7d75b8"),
                            Action = "print",
                            Description = "Print sales orders",
                            ModuleId = "sales.orders"
                        },
                        new
                        {
                            Id = new Guid("1db07341-3ec7-16df-c62a-f7db4a88cdb6"),
                            Action = "view",
                            Description = "View sales returns",
                            ModuleId = "sales.returns"
                        },
                        new
                        {
                            Id = new Guid("6fc00bfb-f3c8-cecc-fbe5-77011199ffb8"),
                            Action = "create",
                            Description = "Create sales returns",
                            ModuleId = "sales.returns"
                        },
                        new
                        {
                            Id = new Guid("6b82f536-a590-abd6-a145-5de8ce231ee0"),
                            Action = "approve",
                            Description = "Approve sales returns",
                            ModuleId = "sales.returns"
                        },
                        new
                        {
                            Id = new Guid("58206a04-d33c-bd77-2cce-969a9503b144"),
                            Action = "export",
                            Description = "Export sales returns",
                            ModuleId = "sales.returns"
                        },
                        new
                        {
                            Id = new Guid("dd3c95f7-4edf-8d02-c910-37c077c289aa"),
                            Action = "print",
                            Description = "Print sales returns",
                            ModuleId = "sales.returns"
                        },
                        new
                        {
                            Id = new Guid("0db8f10b-92af-ded4-3150-a755eb7758d9"),
                            Action = "view",
                            Description = "View purchase vendors",
                            ModuleId = "purchase.vendors"
                        },
                        new
                        {
                            Id = new Guid("45fde95e-6ee2-10f3-34a1-029e5040ea89"),
                            Action = "create",
                            Description = "Create purchase vendors",
                            ModuleId = "purchase.vendors"
                        },
                        new
                        {
                            Id = new Guid("7bd87e96-2bd6-4e36-4208-0afbc79f5ce0"),
                            Action = "edit",
                            Description = "Edit purchase vendors",
                            ModuleId = "purchase.vendors"
                        },
                        new
                        {
                            Id = new Guid("0e67bce5-3a80-d6b6-1415-2a04bbe9ee65"),
                            Action = "delete",
                            Description = "Delete purchase vendors",
                            ModuleId = "purchase.vendors"
                        },
                        new
                        {
                            Id = new Guid("259c60e2-6c13-092a-56f4-3228f1ef41a5"),
                            Action = "export",
                            Description = "Export purchase vendors",
                            ModuleId = "purchase.vendors"
                        },
                        new
                        {
                            Id = new Guid("3ff801b3-862e-b12b-3a91-c87da958fa4e"),
                            Action = "view",
                            Description = "View purchase orders",
                            ModuleId = "purchase.orders"
                        },
                        new
                        {
                            Id = new Guid("8866544e-af18-c401-6d80-b508ac2487eb"),
                            Action = "create",
                            Description = "Create purchase orders",
                            ModuleId = "purchase.orders"
                        },
                        new
                        {
                            Id = new Guid("62598b11-db9c-6015-f02e-8008c4d2210d"),
                            Action = "edit",
                            Description = "Edit purchase orders",
                            ModuleId = "purchase.orders"
                        },
                        new
                        {
                            Id = new Guid("e336c05e-910b-4d5c-e329-67c7c6bb6513"),
                            Action = "approve",
                            Description = "Approve purchase orders",
                            ModuleId = "purchase.orders"
                        },
                        new
                        {
                            Id = new Guid("a2bbfd4e-e9fc-76d4-803a-22189426cf31"),
                            Action = "export",
                            Description = "Export purchase orders",
                            ModuleId = "purchase.orders"
                        },
                        new
                        {
                            Id = new Guid("2873be88-aeaa-4205-9101-fe48fc3a4a34"),
                            Action = "print",
                            Description = "Print purchase orders",
                            ModuleId = "purchase.orders"
                        },
                        new
                        {
                            Id = new Guid("17a109bc-8cc2-5f9c-ec8c-123b7ebb01ec"),
                            Action = "view",
                            Description = "View purchase approvals",
                            ModuleId = "purchase.approvals"
                        },
                        new
                        {
                            Id = new Guid("d21fb540-2870-4296-cc15-be61630c2c26"),
                            Action = "approve",
                            Description = "Approve purchase approvals",
                            ModuleId = "purchase.approvals"
                        },
                        new
                        {
                            Id = new Guid("9bdc65a6-2f43-f578-4638-37de4e7df84c"),
                            Action = "view",
                            Description = "View settings general",
                            ModuleId = "settings.general"
                        },
                        new
                        {
                            Id = new Guid("4bb726b4-4e3a-de23-1b53-d775ae7766ff"),
                            Action = "edit",
                            Description = "Edit settings general",
                            ModuleId = "settings.general"
                        },
                        new
                        {
                            Id = new Guid("dec37dd5-eec5-b587-b5fd-a187b3cf4e1a"),
                            Action = "view",
                            Description = "View settings users",
                            ModuleId = "settings.users"
                        },
                        new
                        {
                            Id = new Guid("03bdd99b-663f-1163-6709-6270d3cba743"),
                            Action = "create",
                            Description = "Create settings users",
                            ModuleId = "settings.users"
                        },
                        new
                        {
                            Id = new Guid("7f915ac1-9c18-f651-d366-2168634329e6"),
                            Action = "edit",
                            Description = "Edit settings users",
                            ModuleId = "settings.users"
                        },
                        new
                        {
                            Id = new Guid("e739ca62-4ba4-0139-5580-da339d74efd3"),
                            Action = "delete",
                            Description = "Delete settings users",
                            ModuleId = "settings.users"
                        },
                        new
                        {
                            Id = new Guid("9cf3758c-cd6d-f2f6-89c0-3936cd62030e"),
                            Action = "view",
                            Description = "View settings roles",
                            ModuleId = "settings.roles"
                        },
                        new
                        {
                            Id = new Guid("edefa0bd-ae66-6cbb-5f1a-536ed8d7be17"),
                            Action = "create",
                            Description = "Create settings roles",
                            ModuleId = "settings.roles"
                        },
                        new
                        {
                            Id = new Guid("ddc9cdce-46f1-e3fc-d666-ff6293b68451"),
                            Action = "edit",
                            Description = "Edit settings roles",
                            ModuleId = "settings.roles"
                        },
                        new
                        {
                            Id = new Guid("5674e6bc-11ec-3e6e-6475-2fa42caf3e78"),
                            Action = "delete",
                            Description = "Delete settings roles",
                            ModuleId = "settings.roles"
                        },
                        new
                        {
                            Id = new Guid("c4ec0c4d-fa44-786c-618c-0a8c0978abed"),
                            Action = "view",
                            Description = "View settings branches",
                            ModuleId = "settings.branches"
                        },
                        new
                        {
                            Id = new Guid("74a7207a-1766-4fb4-efad-f7fe83c35fbd"),
                            Action = "create",
                            Description = "Create settings branches",
                            ModuleId = "settings.branches"
                        },
                        new
                        {
                            Id = new Guid("a06251f8-5567-2b5e-5306-aa6104396053"),
                            Action = "edit",
                            Description = "Edit settings branches",
                            ModuleId = "settings.branches"
                        },
                        new
                        {
                            Id = new Guid("39cbaea2-69dc-b6e9-b4b2-a3b882de67be"),
                            Action = "delete",
                            Description = "Delete settings branches",
                            ModuleId = "settings.branches"
                        },
                        new
                        {
                            Id = new Guid("a364b3d3-7551-ded0-cc05-c406bc7ae159"),
                            Action = "view",
                            Description = "View settings integrations",
                            ModuleId = "settings.integrations"
                        },
                        new
                        {
                            Id = new Guid("1516998e-3131-554f-a927-e3701add1736"),
                            Action = "edit",
                            Description = "Edit settings integrations",
                            ModuleId = "settings.integrations"
                        },
                        new
                        {
                            Id = new Guid("261e3c0b-aa92-361f-b67a-f471fc6377c4"),
                            Action = "view",
                            Description = "View settings audit",
                            ModuleId = "settings.audit"
                        },
                        new
                        {
                            Id = new Guid("e8000586-6ddf-1ad3-3af5-92ba967f2e18"),
                            Action = "export",
                            Description = "Export settings audit",
                            ModuleId = "settings.audit"
                        });
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("system");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionStrings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("system");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeploymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EnabledModules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("tenants", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("system");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("system");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Softaxis.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Softaxis.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Softaxis.Identity.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Softaxis.Identity.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("Softaxis.Identity.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Softaxis.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Softaxis.Identity.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Softaxis.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
