[sqlagent]
enabled = false

[EULA]
accepteula = Y

[memory]
memorylimitmb = 4096

[network]
tcpport = 1433

[filelocation]
defaultdatadir = /var/opt/mssql/data
defaultlogdir = /var/opt/mssql/log
defaultbackupdir = /var/opt/mssql/backup

[telemetry]
customerfeedback = false
